README.md, src/semver
this allows to release the current pre-release version to a normal one.
the new option works with the `--pretend` flag.
the principle is to remove the pre-release and build patterns to keep only the X.Y.Z format
=> add release option

src/semver
Added the --use <version> possibility to "bump" and to "release" commands.
It allows for bypassing the version file, and working with a version directly from command line, i.e:
./semver.sh bump -u 1.2.3 major
will produce: 2.0.0 even if the current file has 4.5.6.
=> Add use a version from command line

src/semver
Also, disallow passing empty parameters. This was introduced in
32eda1cad91699549ad2341f6bd6e296f9a48e5b, and I don't see cases where
it is useful. Perhaps I'm missing something.
=> Error out on missing parameter to `bump'.

README.md, src/semver, test/documentation-test
Some un-used code was left over as part of the changes for v2.0.0
this change removes the remnants.
Also used [shellcheck](http://www.shellcheck.net/) to lint the code
and applied the code changes to resolve the identified issues.
One notable item was due to the use of a variable `split` which is an
actual bash command [split](https://ss64.com/bash/split.html). The
variable was renamed to `parts`.
=> Remove un-used code and fixes linting issues

.travis.yml, Makefile, src/semver, test/documentation-test
Adds lint task to Makefile
Adds use of `make lint` to travis via docker service.
Resolves the last lint issue within test script.
Adds ignore only lint issue within semver. The lint issue is because
the variable is set using `eval` in another function which results
in shellcheck being unable to determine when/if the variable `parts`
was initiatlized with a value.
=> Add lint check to Makefile and travis

Makefile
The user of this package won't necessarily want to install to `/usr/local` (indeed, that directory doesn't even exist on my system). Additionally, package managers would probably like to install the program elsewhere ([example][1]), and without a way to customize the prefix would have to fall back to either patching the Makefile, or doing the installation manually, both of which might break down the line.
By introducing a `PREFIX` variable with a default value of `/usr/local`, the installation prefix can be customized, solving these problems.
[1]: https://github.com/NixOS/nixpkgs/pull/51004
=> Add customizable PREFIX in Makefile

README.md, src/semver, test/documentation-test
Hello,
Due to #27 I've fixed the issue and corresponding test. Also I added '\$' to uniquely match unit test case.
=> Fixed compare 'version' with 'version-prerelease' and documentation-test

src/semver
Allow versions prefixed with `v|V`
=> feat: allow versions prefixed with v|V

README.md, src/semver, test/documentation-test
Fixes #29 
* add TODO: test/documentation-test should also allow testing error-cases.
* add TODO: validation-version does not fully implement semver2.x with regards to numerical prerel identifiers
* fix code comments: prerel and build also allow dots.
* document that semver 2.x is implemented as opposed to semver 1.x or a future version.
=> Update documentation to specify semver 2.0.0

README.md, src/semver
The "release" subcommand now works correctly with the "get" command.
It works as specified in the public API for semver 2.1.0 (README.md),
so this change does not impact the public API: it is a bug fix. An
example and test case has been added to the README.md to cover "get
release".
The public documentation for semver 2.1.0 does not specify a "bump
release" command. However, an example of this command is present in
the 2.1.0 README.md and "bump release" is specified in the script usage
message. Assuming this, the change to the public documentation in this
commit should not be considered as changing the public API (again, this
is a documentation bug fix, not a minor version increment).
README.md has been updated to correspond exactly to the script's usage
message. Not only is the release …
=> "release" subcommand fixed for "get", documentation updated/corrected

Makefile, test/semver.bats, test/semver_2.0.0.bats
Test scripts using the "bats" (https://github.com/bats-core/bats-core)
testing interpreter added in the test directory.  As well, a new target
("unit-test") in the Makefile was added that runs the tests under
Docker using the official bats image.  The scripts include both positive
and negative tests.
The "semver.bats" script addresses the semver-tool CLI, exercising
the commands and sub-commands, options, the optional v|V prefix.
The "semver_2.0.0.bats" script addresses compliance with the semantic
version spec, v2.0.0.  The tests were written largely by following the
spec available at semver.org.  Where the spec includes examples, these
have been included in the test suite.  Most of the tests address:
1) the proper syntax for versions.
2) the rules for precedence (comparison).
Travis now …
=> Unit tests added using the "bats" testing framework.

README.md, src/semver
Change summary:
1. SEMVER_REGEX
SEMVER_REGEX now enforces the rule that numeric id's in the pre-release part
may not have leading zero's.  Alphanumeric id's may have leading zeros.
With the exception of the (permissive) acceptance of a leading "v" or "V",
the RE is now compliant.
The re-written SEMVER_REGEX has been decomposed into defined
sub-expressions to ease understanding of the code and to remove
redundancies.  However, the usage message and public API retain the fully
expanded RE which is now longer and more complex.
Because of changes in the RE groupings, the indexes to captured groups
in BASH_REMATCH have changed.
The SEMVER_REGEX is essentially the same as the Perl version published
by semver.org.  See: semver.org and https://regex101.com/r/vkijKf/1/
The only deltas are that:
1. …
=> semver tool compliant with semver.org spec version 2.0.0

README.md, src/semver, test/semver_2.0.0.bats
Adds a handy command to get the difference between two versions by release type. E.g.
```
semver diff 1.2.3 2.3.4 => "major"
```
=> add diff command

Makefile
Running `make lint` on systems where bash is not linked to /bin/sh causes shellcheck to validate against those shells instead of bash if no explicit shell is selected for checking.
=> Explicitly select shell for shellcheck

src/semver
Closes #44. The function "is-nat" was mistakenly renamed "is:-nat" in a previous clean-up.  This corrects the situation, renaming it to "is_nat", consistent with the previous clean-up.  This PR does not require any version change as no functionality changed, was added, and no bugs were fixed.
=> Rename is:_nat to is_nat. Closes issue #44.

README.md, src/semver, test/bump_prerel.bats, test/semver_2.0.0.bats
Closes #45 
The basic approach is that currently disallowed usages of "bump prerel"
can be used to introduce numerical bumping of a trailing numeric portion of
a PRERELEASE string.
Previously, "bump prerel" required an argument that was simply used as
the new PRERELEASE string; with any BUILD part removed. The argument
needed to be a correct PRERELEASE string. In particular, it could not
contain a trailing dot.
Here, a trailing dot denotes a numeric portion that is either created or
updated. "Updated" means "incremented by one". The previous functionality
(simple replacement) remains. If a trailing dot is present, the
"<prerel>" argument is used as a prototype and the new functionality
is invoked. Note that any BUILD part is always removed.
For example, here a PRERELEASE field with an …
=> Add "bump prerel" with an incrementing numeric portion.

README.md
issues: #48
Tested manually.
N.B.  This PR does not address removing code from the previous CI site (Travis).  The badge, however, is gone.
N.B.  This PR does not touch the github CI code (triggers, labels, etc).
Change does not imply a new release.
If @fsaintjacques does not accept this PR in the next few days, I will accept it myself as it is one liner to the docs and easily reversible.
=> docs: add github action badge for unit tests and linters

README.md
The release badge displays a label dynamically generated from the
latest github release.  Only stable (non pre-release) releases are
considered.  The URL/markdown reflects the recommended form according
to shields.io.
The "click-through" URL is likewise dynamic and points to the latest
release on github. That is, the label and URL are automatically kept
in sync. The previous "tag" badge used a static URL
that needed to be maintained to stay in sync with the dynamic label.
Note that "latest" is determined by date: what the github api
considers latest.
issues: #49
=> docs: replace "tag" badge with "release" badge

README.md
In regards to this issue:
https://github.com/fsaintjacques/semver-tool/issues/59
I have added some information to the read-me about how to install the semver tool with wget and with the [asdf plugin](https://github.com/mathew-fleisch/asdf-semver) I just made. The [asdf version manager](https://asdf-vm.com/) is a neat tool for installing and switching between different versions of release binaries from github.
=> Add installation instructions on read-me

README.md
The installation of "semver" via package/version/dependency managers
has been moved to the end of the README file.  The descriptions have
been shortened and the style/substance describing the two (known)
managers is now consistent.
The details of how to set up the package managers has been removed.
Instead, the reader is referred to the respective web sites.  In this
way, the semver-tool project does not duplicate information and is
not burdened with keeping it acurate, complete, and up to date.
This change addresses github issue #67 (and PR #65).
The basic installation description has been lightly edited.
Not related to this issue, the README file headline list now mentions
the recently added "validate" command.
=> Factor out package manager installation notes (issue #67)

.github/workflows/ci.yaml, README.md
A while back I created an [asdf plugin for semver](https://github.com/mathew-fleisch/asdf-semver) and thought I could also contribute an example of using semver in a github action by installing with the [asdf action](https://github.com/asdf-vm/actions) by refactoring the .github/workflows/ci.yaml file in this repo. Rather than using docker to run bats and shellcheck, asdf can be used to install those as well. After adding bats, shellcheck and semver as "tool-versions" dependencies, display the semver version and help as a verification, lint the code with shellcheck and finally run bats tests. This action is also now configured to run on merges to master as well as commits in pull requests to master.
=> Github Action Example / CI Refactor

README.md, src/semver, test/bump.bats, test/get.bats
The "diff" subcommand returns the keyword "prerelease" when it
is the pre-release part that differs. This keyword--different from
"prerel"--means using the output of "diff" is awkward to use as
input to "bump" or "get".  This change creates a synonym for "prerel",
namely "prerelease" in the bump and get subcommands, fixing the
output/input awkwardness without breaking backwards compatibility.
The implementation is simple: normalize the part keyword to a
canonical string ("prerel").  This is completely transparent to
the external API.
The usage string and README have been updated accordingly.
The changes pass all the existing unit tests: no regression or
backward compatibility issues. Two new test cases added to cover
use of this alternative keyword.
When released, these changes require …
=> "prerelease" keyword supported in bump and get (issue #51)

src/semver, test/general.bats
The semver utility is not widely packaged by distributions. As such projects may wish to incorporate the script directly as a helper to support packaging and versioning of a project.
In such cases, it is important to ensure that the licence of the semver utility is maintained.
Provide an Apache-2.0 SPDX tag [0][1] within the semver script to ensure the licencing is clear.
[0] https://spdx.dev/ids/
[1] https://spdx.org/licenses/Apache-2.0.html
Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>
=> Specify SPDX tag for semver
